apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: capsh
spec:
  shortDescription: check the capabilities(7) of a running Pod.
  homepage: https://github.com/appdevgbb/utils-capsh
  description: |
    check the capabilities(7) of a running Pod.
  caveats: |
    kubectl-capsh needs capsh to run, so when executed for the first time it 
    will download that file from this repository and install it under .kube/capsh 

    Usage:
      kubectl capsh <pod>
  version: v0.1.1
  platforms:
  - selector:
      matchExpressions:
      - key: os
        operator: In
        values:
        - darwin
        - linux
    uri: https://github.com/appdevgbb/utils-capsh/releases/download/v0.1.1/capsh-0.1.1.tar.gz
    sha256: 4711bc72721a3840cb6eebf521572d112d127e904c625b61d7c7bbdc737f27ad
    bin: kubectl-capsh
    files: 
    - from: ./kubectl-capsh
      to: .
    - from: LICENSE
      to: .
